### ISSUE TITLE
The widget is working but not showing in Wibar. Can change the layout with keyboard shortcut.

### ISSUE THREAD

**Issue by z3n-k3rn3l** [echuraev/keyboard_layout#10]
Widget works fine without any startup error and keybinding works fine. The layout is changing, but you know no widget icon showing on the wibar. Added the code to do that as given in the documentation.

**Comment by echuraev** [comment]
Hello @z3n-k3rn3l! Sorry for the delay in the response. Unfortunately, I don't have a machine with AwesomeWM, so I'm not able to check how the plugin works on the latest version of AwesomeWM. Please, double check that you have configured this plugin correctly. Also, please make sure that the icons are existing in the path there the plugin is looking for them.
Also, check that tui mode is works for you. In case if it works, I suggest taking a look on the path to the images.

And in case then something doesn't work, it would be nice if you can fix it and submit a PR. I'll be glad to help you by answering on any questions, but unfortunately, I'm not able to check it and fix in case if something doesn't work.

You can take a look on `function kbdcfg.switch(layout)` in `kbdcfg.lua` and check how it works for you.

**Comment by z3n-k3rn3l** [comment]
Thanks will do that. But anyway I can switch between keyboard layouts. Since I'm only using two keyboard layout this isn't a problem.

**Comment by Octelly** [comment]
@z3n-k3rn3l are you still experiencing this problem?

**Comment by z3n-k3rn3l** [comment]
The problem was closed already back then. Sorry for the delay..
