### ISSUE TITLE
Remember input method per winodw

### ISSUE THREAD

**Issue by krydos** [echuraev/keyboard_layout#2]
Hey @echuraev 
Thanks for the package. 

Don't you know if there is any way to remember what keyboard layout was selected previously for a window? 

Like Chrome has EN and Skype has RU.
When I switch from Skype (RU) to Chrome (EN) the input method is also change. It usually called `Allow different layouts for individual windows`

**Comment by echuraev** [comment]
@asavonic has implemented this functionality for his configuration. I hope he can help you.

**Comment by asavonic** [comment]
Hi @KryDos,

I had this setup before. The idea is pretty simple:

  1. Modify your 'switch layout' function to remember a current layout for a client (a window):
     ```
     function kbd_switch()
         if client.focus then
             local layout = kbdcfg.layouts[kbdcfg.current]
             client.focus.kbd_layout = layout.name
         end

         kbdcfg.switch_next()
     end
     ```

  2. Register a callback to fire when you switch to a new client:
     ```
     client.connect_signal("focus", kbd_client_update)
     ```

  3. In the callback function load the current client layout and switch to it:
     ```
     function kbd_client_update(c)
         if not c then
             return
         end

         if not c.kbd_layout then
            c.kbd_layout = kbdcfg.layouts[1].name
         end

         kbdcfg.switch_by_name(c.kbd_layout)
     end
     ```

Unfortunately, I don't have an AwesomeWM installation at hand, so this code
is completely untested.

**Comment by krydos** [comment]
@asavonic awesome! thank you

**Comment by echuraev** [comment]
@KryDos Did you try this solution? If you use this solution then could you please create PR with adding posibility of remembering input method per window? I think it is nice to have a variable that will help to switch mode.

**Comment by krydos** [comment]
@echuraev nop, didn't try it yet. I guess it should be good reason to dig into Lua. Will try to prepare PR.

**Comment by echuraev** [comment]
@KryDos Ok, thank you!

**Comment by krydos** [comment]
hey @echuraev 
I've just created PR for the new functionality. Basically it's just copy paste of @asavonic 's code (it works with no changes). 

This is my first lines in Lua, so it would be great if you'll leave your feedback. Is it ok that I ask to set variable directly to true instead of call something like `kbdcfg.remember_layout()`?

**Comment by echuraev** [comment]
Hi @KryDos 
I added some comments to your code. You can see it on PR.
