### ISSUE TITLE
kbdcfg not found

### ISSUE THREAD

**Issue by ion-lane** [echuraev/keyboard_layout#5]
Awesome cannot find a command kbdcfg. Which package do i need to install?

**Comment by echuraev** [comment]
Hi @ion-lane,

I can suggest that awesome cannot find directory that contains the widget. Could you please describe how do you try to install the keyboard_layout widget?

**Comment by ion-lane** [comment]
Надеюсь ,я могу ответить по-русски?
Разобрался в чем была проблема, похоже я не в те места конфиг вставлял. Объявлял модули в конце, а нужно было в начале. Настроил заново и все заработало.

Возникли трудности в 5 пункотом инструкции.
Нашел у себя код виджетов справа, но не пойму что именно туда прописывать?
```
   -- Create the wibox
    mywibox[s] = awful.wibox({ position = "top", screen = s })

    -- Widgets that are aligned to the left
local left_layout = wibox.layout.fixed.horizontal()
    left_layout:add(mylauncher)
    left_layout:add(mytaglist[s])
    left_layout:add(mypromptbox[s])

    -- Widgets that are aligned to the right
    local right_layout = wibox.layout.fixed.horizontal()
    if s == 1 then right_layout:add(wibox.widget.systray()) end
    right_layout:add(mytextclock)
    right_layout:add(mylayoutbox[s])

    -- Now bring it all together (with the tasklist in the middle)
    local layout = wibox.layout.align.horizontal()
    layout:set_left(left_layout)
    layout:set_middle(mytasklist[s])
    layout:set_right(right_layout)

    mywibox[s]:set_widget(layout)

```

**Comment by echuraev** [comment]
На будущее, пишите, пожалуйста, по-английски, чтобы кто-то из людей не знающих русский мог прочитать Ваш вопрос.
Необходимо добавить виджет на панель, например так:
```
    -- Widgets that are aligned to the right
    local right_layout = wibox.layout.fixed.horizontal()
    if s == 1 then right_layout:add(wibox.widget.systray()) end
    right_layout:add(kbdcfg.widget)
    right_layout:add(mytextclock)
    right_layout:add(mylayoutbox[s])
```
Разница в конфигах из-за того, что у Вас версия Awesome WM 3.5, а настройка описана для Awesome WM 4.x.
