### ISSUE TITLE
Caps lock

### ISSUE THREAD

**Issue by Ladone** [echuraev/keyboard_layout#7]
How I can map CAPS LOCK switching language?

**Comment by echuraev** [comment]
Hi @Ladone !

You have to take a look on the point number 4 in [Usage section](https://github.com/echuraev/keyboard_layout#Usage). You have to add your binding for `CapsLock`. `CapsLock` modifier is `"Lock"`.
So, based on this [description](https://awesomewm.org/doc/api/libraries/awful.key.html#new), I can suggest that it should be something like that:

```lua
globalkeys = awful.util.table.join(globalkeys,
    -- CapsLock to change keyboard layout
    awful.key({}, "Lock", function () kbdcfg.switch_next() end)
)
```

Unfortunately, I don't have a linux machine with Awesome WM right now and I'm not able to check it. Could you please let me know how it will work for you?
If `"Lock"` modifier won't work, please, try the following: `"CapsLock"` or `"Caps_Lock"`. I hope it should works.

Thank you in advance!

**Comment by Ladone** [comment]
Caps_Lock - work for me, thanks (spasibo a.k.a. спасибо) ;)

**Comment by Ladone** [comment]
But I stuck with problem work capslock, he not disable SELF-FUNCTIONS :с
Caps_Lock - work for me, thanks (spasibo a.k.a. спасибо) ;)
